deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull Docker image
        run: docker pull deena9865/swiggy-clone:latest
        
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.29.2/trivy_0.29.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.29.2_Linux-64bit.deb
          
      - name: Image scan
        run: trivy image deena9865/swiggy-clone:latest > trivyimagedeploy.txt
        
      - name: Deploy to container
        run: |
          # Stop and remove any existing container with the same name
          docker stop swiggy-clone || true
          docker rm swiggy-clone || true
          # Run the new container
          docker run -d --name swiggy-clone -p 3000:3000 deena9865/swiggy-clone:latest
