name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: NPM Install
        run: npm install

      - name: Docker build and push
        env:
          DOCKER_CLI_ACI: 1
        run: |
          # Build Docker image
          docker build -t swiggy-clone .
          # Tag Docker image
          docker tag swiggy-clone deena9865/swiggy-clone:latest
          # Log in to Docker Hub
          echo "${{ secrets.Dockerhub_token }}" | docker login -u "${{ secrets.Dockerhub_username }}" --password-stdin
          # Push Docker image
          docker push deena9865/swiggy-clone:latest

